artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Akshay-a-j/MLBCP/raw/main/data_bcp.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv

model_trainer:
  root_dir: artifacts/Model_trainer
  X_train_path: artifacts/data_transformation/X_train_resampled.csv
  Y_train_path: artifacts/data_transformation/y_train_resampled.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/Model_evaluation
  X_test_path: artifacts/data_transformation/X_test.csv
  Y_test_path: artifacts/data_transformation/y_test.csv
  model_path: artifacts/Model_trainer/model.joblib


